#pragma once
#include <cassert>
#include <chrono>
#include <functional>
#include <iomanip>
#include <iostream>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <random>
#include <set>
#include <sstream>
#include <string>
#include <vector>
#include <stdio.h>
#include <WinSock2.h>
#include <WS2tcpip.h>
using namespace std;